<?php
/**
 * @file
 * Code for the Hide Author module.
 */

// TODO Create an admin page for users to peruse who actually posted stuff.

function hide_author_node_insert($node) {
  if ($node->type == 'confession' && $node->field_anonymous_post['und'][0]['value'] && $node->is_new) {
    $record = array('nid' => $node->nid, 'uid' => $node->uid);
    drupal_write_record('hide_author', $record);
    $node->uid = 0;
    drupal_write_record('node', $node, 'nid');
  }
}
